import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Container, Row, Col, Card } from 'react-bootstrap';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>360PRAYER</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Container fluid>
                    <Row fluid style={{
                        height: "30vh"
                    }}>
                        <Col className="Text-Title" style={{
                            height: "30vh",
                            display: "flex",
                            flexDirection: 'column',
                            justifyContent: 'center',
                            alignItems: 'center',
                            fontSize: "40px",
                            lineHeight: "125%",
                            fontWeight: "600"



                        }}>
                            Learning to honor the First, <br />
                            So we can honor the second.
                        </Col>
                    </Row>
                    <Row >
                        <Col s={12} className="Hero-Col">
                            <Card>
                                <Card.Body tyle={{fontSize:"24px"}}>
                                    <h2>The Issue </h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo laborum, autem corporis repudiandae reiciendis doloribus ad placeat maiores necessitatibus accusantium odit culpa perspiciatis nulla blanditiis, obcaecati saepe, explicabo eaque pariatur.
                                </Card.Body>
                            </Card>

                        </Col>

                        <Col s={12} className="Hero-Col">
                            <Card>
                                <Card.Body>
                                    <h2>The Solution </h2>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo laborum, autem corporis repudiandae reiciendis doloribus ad placeat maiores necessitatibus accusantium odit culpa perspiciatis nulla blanditiis, obcaecati saepe, explicabo eaque pariatur.
                                </Card.Body>
                            </Card> </Col>
                    </Row>
                </Container>

            </main>

            <footer className={styles.footer}>
                FOOTER
            </footer>
        </div>
    )
}
